## environment.yml (Python Environment)

name: price_forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - numpy
  - matplotlib
  - scikit-learn
  - statsmodels
  - jupyterlab
  - jupyter
  - plotly
  - pytorch
  - pytest
  - requests
  - properscoring
  - optuna
  - pip
  - pip:
      - -e .
