## 📦 environment.yml (Python Environment)

name: nodal-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyterlab
  - jupyter
  - plotly
  - pymc
  - arviz
  - pyro-ppl
  - pytorch
  - requests
  - beautifulsoup4
  - sqlalchemy
  - pip
  - lightgbm
  - shap
  - pip:
      - PyBATS
      - orbit-ml
      - streamlit
      - pycaiso
      - properscoring
