## 📦 environment.yml (Python Environment)

name: nodal-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - statsmodels
  - jupyterlab
  - jupyter
  - plotly
  - pymc
  - pytorch
  - pytest
  - requests
  - lightgbm
  - shap
  - properscoring
  - optuna
  - pip
  - pip:
      - -e .
