model: "EncoderDecoder"
batch_size: 8
data_source: v1
dropout: 0.5
epochs: 100
hidden_size: 64
learning_rate: 0.001
weight_decay: 0.001
quantiles:
- 0.01
- 0.05
- 0.1
- 0.25
- 0.5
- 0.75
- 0.9
- 0.95
- 0.99
